CORE-3005 Add disk_type support
castai/terraform-castai-gke-cluster pull request #35
Opened 2023-07-03 09:22 UTC by apasyniuk

2023-07-03 09:38 UTC, fals approved these changes

2023-07-03 10:16 UTC, Narunas-K reviewed
versions.tf would need to be updated with latest provider version after its' change is merged. e.g. of simillar change in EKS  module https://github.com/castai/terraform-castai-eks-cluster/commit/0573ae73f9ec475a71f03d83b240fe247f856bc1

2023-07-03 10:25 UTC, Narunas-K requested changes
versions.tf would need to be updated with latest provider version after its' change is merged. e.g. of similar change in EKS  module https://github.com/castai/terraform-castai-eks-cluster/commit/0573ae73f9ec475a71f03d83b240fe247f856bc1

2023-07-04 09:13 UTC, apasyniuk commented
@Narunas-K Version changed to 3.13.0.

2023-07-04 11:10 UTC, merged